### GET Ebook List by Name
GET http://localhost:8080/ebooks?name=Python
Content-Type: application/json


### GET Ebook List by id
GET http://localhost:8080/ebooks?page=1&size=10
Content-Type: application/json



### Update Ebook
POST http://localhost:8080/ebooks
Content-Type: application/json

{
  "id": 3,
  "name": "Python 入门教程",
  "description": "零基础入门Python开发，企业级应用开发最佳首选框架, 值得选择"
}


### Update Ebook
POST http://localhost:8080/ebooks
Content-Type: application/json

{
  "name": "Mongodb 入门教程",
  "description": "零基础入门Mongodb开发，企业级应用开发最佳首选框架"
}


### GET Ebook By id
GET http://localhost:8080/ebooks/3
Content-Type: application/json
